{{- if .Values.rbac.create }}

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "platform-health.fullname" . }}-node-reader
rules:
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - get
      - list

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "platform-health.fullname" . }}-node-reader
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "platform-health.fullname" . }}-node-reader
subjects:
  - kind: ServiceAccount
    name: {{ .Values.serviceAccount.name }}
    namespace: {{ .Release.Namespace }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "platform-health.fullname" . }}-awx-reader
  namespace: {{ .Values.config.kubernetesNamespace }}
rules:
  - apiGroups:
      - apps
    resources:
      - deployments
      - deployments/status
      - statefulsets
      - statefulsets/status
    verbs:
      - get

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "platform-health.fullname" . }}-awx-reader
  namespace: {{ .Values.config.kubernetesNamespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "platform-health.fullname" . }}-awx-reader
subjects:
  - kind: ServiceAccount
    name: {{ .Values.serviceAccount.name }}
    namespace: {{ .Release.Namespace }}

{{- end }}
